version: '3'
services:
  productoschain-react:
    container_name: productoschain-react
    hostname: productoschain-react
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - productoschain-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 50M

networks:
  productoschain-net:
    driver: bridge